# Space Invaders - Urbana Board Constraints
# Spartan-7 xc7s50csga324-1

# --- Bank voltage / config ---
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property INTERNAL_VREF 0.675 [get_iobanks 34]

# --- 200 MHz differential DDR reference clock ---
set_property PACKAGE_PIN C1 [get_ports sys_clk_p]
set_property PACKAGE_PIN B1 [get_ports sys_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports sys_clk_p]
set_property IOSTANDARD LVDS_25 [get_ports sys_clk_n]
create_clock -period 10.000 -name sys_clk [get_ports sys_clk_p]

# --- Reset (active-low) ---
set_property PACKAGE_PIN J2 [get_ports cpu_resetn]
set_property IOSTANDARD LVCMOS25 [get_ports cpu_resetn]

# --- HDMI TX ---
set_property PACKAGE_PIN U16 [get_ports hdmi_clk_p]
set_property PACKAGE_PIN V17 [get_ports hdmi_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_n]

set_property PACKAGE_PIN U17 [get_ports {hdmi_tx_p[0]}]
set_property PACKAGE_PIN U18 [get_ports {hdmi_tx_n[0]}]
set_property PACKAGE_PIN R16 [get_ports {hdmi_tx_p[1]}]
set_property PACKAGE_PIN R17 [get_ports {hdmi_tx_n[1]}]
set_property PACKAGE_PIN R14 [get_ports {hdmi_tx_p[2]}]
set_property PACKAGE_PIN T14 [get_ports {hdmi_tx_n[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_tx_p[*]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_tx_n[*]}]

# --- UART ---
set_property PACKAGE_PIN B16 [get_ports uart_txd]
set_property PACKAGE_PIN A16 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]

# --- GPIO 0 (switches SW[15:0] on bits [15:0], buttons BTN[3:0] on bits [19:16]) ---
set_property PACKAGE_PIN G1  [get_ports {gpio_0[0]}]
set_property PACKAGE_PIN F2  [get_ports {gpio_0[1]}]
set_property PACKAGE_PIN F1  [get_ports {gpio_0[2]}]
set_property PACKAGE_PIN E2  [get_ports {gpio_0[3]}]
set_property PACKAGE_PIN E1  [get_ports {gpio_0[4]}]
set_property PACKAGE_PIN D2  [get_ports {gpio_0[5]}]
set_property PACKAGE_PIN D1  [get_ports {gpio_0[6]}]
set_property PACKAGE_PIN C2  [get_ports {gpio_0[7]}]
set_property PACKAGE_PIN B2  [get_ports {gpio_0[8]}]
set_property PACKAGE_PIN A4  [get_ports {gpio_0[9]}]
set_property PACKAGE_PIN A5  [get_ports {gpio_0[10]}]
set_property PACKAGE_PIN A6  [get_ports {gpio_0[11]}]
set_property PACKAGE_PIN C7  [get_ports {gpio_0[12]}]
set_property PACKAGE_PIN A7  [get_ports {gpio_0[13]}]
set_property PACKAGE_PIN B7  [get_ports {gpio_0[14]}]
set_property PACKAGE_PIN A8  [get_ports {gpio_0[15]}]
set_property PACKAGE_PIN J1  [get_ports {gpio_0[16]}]
set_property PACKAGE_PIN G2  [get_ports {gpio_0[17]}]
set_property PACKAGE_PIN H2  [get_ports {gpio_0[18]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[16]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[17]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gpio_0[18]}]

# --- GPIO 1 (LEDs[15:0] on bits [15:0]) ---
set_property PACKAGE_PIN C13 [get_ports {gpio_1[0]}]
set_property PACKAGE_PIN C14 [get_ports {gpio_1[1]}]
set_property PACKAGE_PIN D14 [get_ports {gpio_1[2]}]
set_property PACKAGE_PIN D15 [get_ports {gpio_1[3]}]
set_property PACKAGE_PIN D16 [get_ports {gpio_1[4]}]
set_property PACKAGE_PIN F18 [get_ports {gpio_1[5]}]
set_property PACKAGE_PIN E17 [get_ports {gpio_1[6]}]
set_property PACKAGE_PIN D17 [get_ports {gpio_1[7]}]
set_property PACKAGE_PIN C17 [get_ports {gpio_1[8]}]
set_property PACKAGE_PIN B18 [get_ports {gpio_1[9]}]
set_property PACKAGE_PIN A17 [get_ports {gpio_1[10]}]
set_property PACKAGE_PIN B17 [get_ports {gpio_1[11]}]
set_property PACKAGE_PIN C18 [get_ports {gpio_1[12]}]
set_property PACKAGE_PIN D18 [get_ports {gpio_1[13]}]
set_property PACKAGE_PIN E18 [get_ports {gpio_1[14]}]
set_property PACKAGE_PIN G17 [get_ports {gpio_1[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_1[15]}]

# --- USB SPI (MAX3421E) ---
set_property PACKAGE_PIN V14 [get_ports usb_sclk]
set_property PACKAGE_PIN V15 [get_ports usb_mosi]
set_property PACKAGE_PIN U12 [get_ports usb_miso]
set_property PACKAGE_PIN T12 [get_ports usb_ss_n]
set_property IOSTANDARD LVCMOS33 [get_ports usb_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports usb_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports usb_miso]
set_property IOSTANDARD LVCMOS33 [get_ports usb_ss_n]

# --- Unused upper GPIO bits (AXI GPIO IP is 32-bit wide; bits above physical pins are unconnected) ---
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]
