#include "usb_hid.h"
#include "xparameters.h"

#if defined(XPAR_SPI_USB_BASEADDR)
#  define SPI_BASE XPAR_SPI_USB_BASEADDR
#  define USB_HID_SPI_PRESENT
#elif defined(XPAR_SPI_0_BASEADDR)
#  define SPI_BASE XPAR_SPI_0_BASEADDR
#  define USB_HID_SPI_PRESENT
#endif

/*
 * Vivado mapping for the dedicated USB MAX3421E GPIOs:
 *   AXI_GPIO_2 bit 0 -> usb_rst_n
 *   AXI_GPIO_3 bit 0 <- usb_int_n
 *
 * The IP names are left as generated by Vivado; keep the readable aliases
 * here so the rest of the driver does not depend on generic GPIO numbers.
 */
#if defined(XPAR_AXI_GPIO_2_BASEADDR) && defined(XPAR_AXI_GPIO_3_BASEADDR)
#  define USB_RST_GPIO_BASEADDR XPAR_AXI_GPIO_2_BASEADDR
#  define USB_INT_GPIO_BASEADDR XPAR_AXI_GPIO_3_BASEADDR
#  define USB_HID_GPIO_PRESENT
#endif

#ifdef USB_HID_SPI_PRESENT

typedef unsigned char  BYTE;
typedef unsigned short WORD;

/* AXI GPIO direct register access for usb_rst_n / usb_int_n */
#ifdef USB_HID_GPIO_PRESENT
#define GPIO_REG(base, off) (*(volatile uint32_t *)((base) + (uint32_t)(off)))
#define GPIO_DATA_OFFSET    0x0000u
#define GPIO_TRI_OFFSET     0x0004u
#define USB_RST_DATA        GPIO_REG(USB_RST_GPIO_BASEADDR, GPIO_DATA_OFFSET)
#define USB_RST_TRI         GPIO_REG(USB_RST_GPIO_BASEADDR, GPIO_TRI_OFFSET)
#define USB_INT_DATA        GPIO_REG(USB_INT_GPIO_BASEADDR, GPIO_DATA_OFFSET)
#define USB_INT_TRI         GPIO_REG(USB_INT_GPIO_BASEADDR, GPIO_TRI_OFFSET)
#define USB_GPIO_BIT0       0x00000001u
#endif

/* AXI Quad SPI direct register access */
#define SPI_REG(off)    (*(volatile uint32_t *)((SPI_BASE) + (uint32_t)(off)))
#define SPI_DGIER       SPI_REG(0x1Cu)
#define SPI_SRR         SPI_REG(0x40u)
#define SPI_CR          SPI_REG(0x60u)
#define SPI_SR          SPI_REG(0x64u)
#define SPI_DTR         SPI_REG(0x68u)
#define SPI_DRR         SPI_REG(0x6Cu)
#define SPI_SSR         SPI_REG(0x70u)

#define SPI_CR_ENABLE   0x002u
#define SPI_CR_MASTER   0x004u
#define SPI_CR_TXRST    0x020u
#define SPI_CR_RXRST    0x040u
#define SPI_CR_MAN_SS   0x080u
#define SPI_CR_INHIBIT  0x100u
#define SPI_SR_RX_EMPTY 0x001u
#define SPI_CR_BASE     ((uint32_t)(SPI_CR_ENABLE|SPI_CR_MASTER|SPI_CR_MAN_SS|SPI_CR_INHIBIT))

#define spi_ss(assert)  (SPI_SSR = (assert) ? 0u : 1u)

/* MAX3421E registers */
#define rRCVFIFO      0x08u
#define rSUDFIFO      0x20u
#define rRCVBC        0x30u
#define rUSBIRQ       0x68u
#define bmOSCOKIRQ    0x01u
#define rUSBCTL       0x78u
#define bmCHIPRES     0x20u
#define rPINCTL       0x88u
#define bmFDUPSPI     0x10u
#define bmINTLEVEL    0x08u
#define bmGPXB        0x02u
#define rIOPINS1      0xa0u
#define bmGPOUT0      0x01u
#define rHIRQ         0xc8u
#define bmBUSEVENTIRQ 0x01u
#define bmRCVDAVIRQ   0x04u
#define bmFRAMEIRQ    0x40u
#define bmHXFRDNIRQ   0x80u
#define rMODE         0xd8u
#define bmHOST        0x01u
#define bmLOWSPEED    0x02u
#define bmSOFKAENAB   0x08u
#define bmSEPIRQ      0x10u
#define bmDMPULLDN    0x40u
#define bmDPPULLDN    0x80u
#define MODE_FS_HOST  (bmDPPULLDN|bmDMPULLDN|bmHOST|bmSOFKAENAB)
#define MODE_LS_HOST  (bmDPPULLDN|bmDMPULLDN|bmHOST|bmLOWSPEED|bmSOFKAENAB)
#define rPERADDR      0xe0u
#define rHCTL         0xe8u
#define bmBUSRST      0x01u
#define bmSAMPLEBUS   0x04u
#define bmRCVTOG0     0x10u
#define bmRCVTOG1     0x20u
#define bmRCVTOGRD    0x10u
#define bmJSTATUS     0x80u
#define bmKSTATUS     0x40u
#define rHXFR         0xf0u
#define tokSETUP      0x10u
#define tokIN         0x00u
#define tokINHS       0x80u
#define rHRSL         0xf8u
#define hrSUCCESS     0x00u
#define hrNAK         0x04u

#define bmREQ_SET        0x00u
#define bmREQ_HIDOUT     0x21u
#define USB_REQUEST_SET_ADDRESS       5u
#define USB_REQUEST_SET_CONFIGURATION 9u
#define HID_REQUEST_SET_PROTOCOL      0x0bu
#define BOOT_PROTOCOL                 0x00u

#define HID_LEFT  0x50u
#define HID_RIGHT 0x4fu
#define HID_SPACE 0x2cu
#define HID_ENTER 0x28u
#define HID_R     0x15u

/* SPI buffers: 1 cmd byte + 8 data bytes = 9 max (fits 16-deep FIFO) */
static BYTE s_spi_tx[9];
static BYTE s_spi_rx[9];

/* EP1 receive data toggle (replaces EP_RECORD/DEV_RECORD/devtable) */
static BYTE s_ep1_rcv_toggle;

/* Set to 1 on first SPI timeout; makes all subsequent spi_xfer calls no-ops */
static uint8_t s_spi_dead;

/* Keyboard held and edge-detect state */
static uint8_t s_left_held;
static uint8_t s_right_held;
static uint8_t s_space_edge;
static uint8_t s_enter_edge;
static uint8_t s_r_edge;
static uint8_t s_space_held;
static uint8_t s_enter_held;
static uint8_t s_r_held;

/* Status word: compiled-in, spi_dead, osc_ok, report_seen, HRSL, poll_rc. */
static uint32_t s_status_word;

#define STAT_COMPILED_IN      0x00008000u
#define STAT_SPI_DEAD         0x00004000u
#define STAT_OSC_OK           0x00002000u
#define STAT_REPORT_SEEN      0x00001000u
#define STAT_HRSL_SHIFT       6u
#define STAT_POLL_MASK        0x0000003fu

/* -----------------------------------------------------------------------
 * SPI core: load TX FIFO, start, drain RX FIFO.
 * --------------------------------------------------------------------- */
static void spi_xfer(BYTE len)
{
    BYTE i;
    WORD t;
    if (s_spi_dead) return;
    SPI_CR = SPI_CR_BASE | (uint32_t)(SPI_CR_TXRST | SPI_CR_RXRST);
    for (i = 0u; i < len; i++) SPI_DTR = s_spi_tx[i];
    SPI_CR = (uint32_t)(SPI_CR_ENABLE | SPI_CR_MASTER | SPI_CR_MAN_SS);
    for (i = 0u; i < len; i++) {
        for (t = 0u; t < 2000u; t++) {
            if ((SPI_SR & SPI_SR_RX_EMPTY) == 0u) break;
        }
        if (t >= 2000u) {
            SPI_CR = SPI_CR_BASE;
            s_spi_dead = 1u;
            s_status_word |= STAT_SPI_DEAD;
            return;
        }
        s_spi_rx[i] = (BYTE)SPI_DRR;
    }
    SPI_CR = SPI_CR_BASE;
}

static BYTE MAXreg_op(BYTE cmd, BYTE val)
{
    s_spi_tx[0] = cmd;
    s_spi_tx[1] = val;
    spi_ss(1u);
    spi_xfer(2u);
    spi_ss(0u);
    return s_spi_rx[1];
}
#define MAXreg_wr(r, v) (void)MAXreg_op((BYTE)((r) | 0x02u), (v))
#define MAXreg_rd(r)    MAXreg_op((r), 0x00u)

/* -----------------------------------------------------------------------
 * XferDispatchPkt — dispatch one USB token; retry on NAK only.
 * Poll limit of 500 SPI reads (~2.5 ms) prevents an infinite hang when
 * the MAX3421E is absent or MISO is stuck low.  Returns 0xFF on timeout.
 * --------------------------------------------------------------------- */
static BYTE XferDispatchPkt(BYTE token, BYTE ep)
{
    BYTE rcode;
    BYTE retry;
    WORD t;
    for (retry = 0u; retry < 16u; retry++) {
        MAXreg_wr(rHXFR, (BYTE)(token | ep));
        for (t = 0u; t < 500u; t++) {
            if (MAXreg_rd(rHIRQ) & bmHXFRDNIRQ) break;
        }
        if (t >= 500u) return 0xffu;   /* timeout: MAX3421E not responding */
        MAXreg_wr(rHIRQ, bmHXFRDNIRQ);
        rcode = (BYTE)(MAXreg_rd(rHRSL) & 0x0fu);
        if (rcode != hrNAK) return rcode;
    }
    return rcode;
}

/* -----------------------------------------------------------------------
 * send_setup_nodata — SETUP + status-IN for H2D zero-data control transfers.
 * Writes 8-byte setup packet directly into SUDFIFO via s_spi_tx.
 * --------------------------------------------------------------------- */
static BYTE send_setup_nodata(BYTE addr, BYTE bmReqType, BYTE bRequest,
                               BYTE wValLo, BYTE wValHi, WORD wInd)
{
    MAXreg_wr(rPERADDR, addr);
    s_spi_tx[0] = (BYTE)(rSUDFIFO | 0x02u);
    s_spi_tx[1] = bmReqType;           s_spi_tx[2] = bRequest;
    s_spi_tx[3] = wValLo;              s_spi_tx[4] = wValHi;
    s_spi_tx[5] = (BYTE)wInd;          s_spi_tx[6] = (BYTE)(wInd >> 8u);
    s_spi_tx[7] = 0u;                  s_spi_tx[8] = 0u;
    spi_ss(1u); spi_xfer(9u); spi_ss(0u);
    if (XferDispatchPkt(tokSETUP, 0u)) return 0xffu;
    return XferDispatchPkt(tokINHS, 0u);
}

/* -----------------------------------------------------------------------
 * XferInTransfer — read one interrupt-IN packet from EP1 into data[0..7].
 * RCVFIFO read is inlined (no separate MAXbytes_rd function).
 * --------------------------------------------------------------------- */
static BYTE XferInTransfer(BYTE *data)
{
    BYTE rcode, pktsize, i;
    MAXreg_wr(rHCTL, s_ep1_rcv_toggle);
    rcode = XferDispatchPkt(tokIN, 1u);
    if (rcode) return rcode;
    if ((MAXreg_rd(rHIRQ) & bmRCVDAVIRQ) == 0u) {
        return 0xf0u;
    }
    pktsize = MAXreg_rd(rRCVBC);
    if (pktsize > 8u) pktsize = 8u;
    if (pktsize > 0u) {
        s_spi_tx[0] = rRCVFIFO;
        for (i = 0u; i < pktsize; i++) s_spi_tx[i + 1u] = 0u;
        spi_ss(1u); spi_xfer((BYTE)(pktsize + 1u)); spi_ss(0u);
        for (i = 0u; i < pktsize; i++) data[i] = s_spi_rx[i + 1u];
    }
    MAXreg_wr(rHIRQ, bmRCVDAVIRQ);
    s_ep1_rcv_toggle = (MAXreg_rd(rHRSL) & bmRCVTOGRD) ? bmRCVTOG1 : bmRCVTOG0;
    return 0u;
}

/* -----------------------------------------------------------------------
 * parse_report — update keyboard state from 8-byte HID boot report.
 * buf[0]=modifier, buf[1]=reserved, buf[2..7]=keycodes.
 * --------------------------------------------------------------------- */
static void parse_report(const BYTE *buf)
{
    BYTE i, k;
    BYTE new_space = 0u, new_enter = 0u, new_r = 0u;
    s_left_held  = 0u;
    s_right_held = 0u;
    for (i = 2u; i < 8u; i++) {
        k = buf[i];
        if (k == HID_LEFT)  s_left_held  = 1u;
        if (k == HID_RIGHT) s_right_held = 1u;
        if (k == HID_SPACE) new_space = 1u;
        if (k == HID_ENTER) new_enter = 1u;
        if (k == HID_R)     new_r     = 1u;
    }
    if (!s_space_held && new_space) s_space_edge = 1u;
    if (!s_enter_held && new_enter) s_enter_edge = 1u;
    if (!s_r_held     && new_r)     s_r_edge     = 1u;
    s_space_held = new_space;
    s_enter_held = new_enter;
    s_r_held     = new_r;
}

/* -----------------------------------------------------------------------
 * blind_connect — bus reset + SOF + SET_ADDRESS/CONFIG/PROTOCOL.
 * Assumes standard HID boot keyboard: addr 1, config 1, EP1 interrupt-IN.
 * Called once from usb_hid_init; no reconnect on disconnect.
 * --------------------------------------------------------------------- */
static BYTE blind_connect(void)
{
    BYTE busstate;
    BYTE rcode;
    unsigned int i;

    busstate = (BYTE)(MAXreg_rd(rHRSL) & (bmJSTATUS | bmKSTATUS));
    s_status_word = (s_status_word & ~(0x03u << STAT_HRSL_SHIFT)) |
                    (((uint32_t)(busstate >> 6u) & 0x03u) << STAT_HRSL_SHIFT);
    MAXreg_wr(rMODE, (busstate == bmJSTATUS) ? MODE_FS_HOST : MODE_LS_HOST);
    for (i = 0u; i < 20000u; i++) { (void)MAXreg_rd(rHIRQ); }

    MAXreg_wr(rHIRQ, bmBUSEVENTIRQ);
    MAXreg_wr(rHCTL, bmBUSRST);
    for (i = 0u; i < 50000u; i++) {
        if ((MAXreg_rd(rHCTL) & bmBUSRST) == 0u) break;
    }
    MAXreg_wr(rMODE, (BYTE)(MAXreg_rd(rMODE) | bmSOFKAENAB));
    for (i = 0u; i < 50000u; i++) {
        if (MAXreg_rd(rHIRQ) & bmFRAMEIRQ) break;
    }

    rcode = send_setup_nodata(0u, bmREQ_SET, USB_REQUEST_SET_ADDRESS, 1u, 0u, 0u);
    if (rcode) return 0xffu;
    for (i = 0u; i < 200000u; i++) { (void)MAXreg_rd(rHIRQ); }
    rcode = send_setup_nodata(1u, bmREQ_SET, USB_REQUEST_SET_CONFIGURATION, 1u, 0u, 0u);
    if (rcode) return 0xffu;
    rcode = send_setup_nodata(1u, bmREQ_HIDOUT, HID_REQUEST_SET_PROTOCOL, BOOT_PROTOCOL, 0u, 0u);
    if (rcode) return 0xffu;

    s_ep1_rcv_toggle = bmRCVTOG0;
    return 0u;
}

/* -----------------------------------------------------------------------
 * Public API
 * --------------------------------------------------------------------- */
int usb_hid_init(void)
{
    unsigned int i;
    BYTE usbirq_after_reset;

    s_status_word = STAT_COMPILED_IN | STAT_POLL_MASK;
    s_spi_dead = 0u;
    s_left_held = 0u;
    s_right_held = 0u;
    s_space_edge = 0u;
    s_enter_edge = 0u;
    s_r_edge = 0u;
    s_space_held = 0u;
    s_enter_held = 0u;
    s_r_held = 0u;
    SPI_SRR   = 0x0Au;
    for (i = 0u; i < 200u; i++) { (void)i; }
    SPI_DGIER = 0u;
    SPI_CR    = SPI_CR_BASE;
    SPI_SSR   = 1u;

    MAXreg_wr(rPINCTL, (BYTE)(bmFDUPSPI | bmINTLEVEL | bmGPXB));
    MAXreg_wr(rUSBCTL, bmCHIPRES);
    MAXreg_wr(rUSBCTL, 0x00u);
    for (i = 0u; i < 50000u; i++) {
        usbirq_after_reset = MAXreg_rd(rUSBIRQ);
        if (usbirq_after_reset & bmOSCOKIRQ) break;
    }
    if (usbirq_after_reset & bmOSCOKIRQ) s_status_word |= STAT_OSC_OK;

    MAXreg_wr(rIOPINS1, (BYTE)(MAXreg_rd(rIOPINS1) | bmGPOUT0));
    MAXreg_wr(rMODE, (BYTE)(bmDPPULLDN | bmDMPULLDN | bmHOST | bmSEPIRQ));
    MAXreg_wr(rHCTL, bmSAMPLEBUS);

    /* Wait up to ~50K polls for device to appear, then try blind connect */
    for (i = 0u; i < 50000u; i++) {
        BYTE hrsl = (BYTE)(MAXreg_rd(rHRSL) & (bmJSTATUS | bmKSTATUS));
        s_status_word = (s_status_word & ~(0x03u << STAT_HRSL_SHIFT)) |
                        (((uint32_t)(hrsl >> 6u) & 0x03u) << STAT_HRSL_SHIFT);
        if (hrsl) break;
    }
    (void)blind_connect(); /* failure is reported through diagnostics */
    return 0;
}

/* usb_hid_poll: read one report from EP1 and update state flags.
 * kbd_buf is a local; no BSS cost. */
void usb_hid_poll(void)
{
    BYTE kbd_buf[8];
    BYTE rc;

    MAXreg_wr(rPERADDR, 1u);
    rc = XferInTransfer(kbd_buf);
    s_status_word = (s_status_word & ~STAT_POLL_MASK) | ((uint32_t)rc & STAT_POLL_MASK);
    if (rc == hrSUCCESS) {
        s_status_word |= STAT_REPORT_SEEN;
        parse_report(kbd_buf);
    }
}

uint8_t usb_hid_left_held(void)  { return s_left_held;  }
uint8_t usb_hid_right_held(void) { return s_right_held; }

uint8_t usb_hid_space_pressed(void)
    { uint8_t v = s_space_edge; s_space_edge = 0u; return v; }
uint8_t usb_hid_enter_pressed(void)
    { uint8_t v = s_enter_edge; s_enter_edge = 0u; return v; }
uint8_t usb_hid_r_pressed(void)
    { uint8_t v = s_r_edge; s_r_edge = 0u; return v; }

uint32_t usb_hid_status_word(void)
{
    return s_status_word;
}

#else

int     usb_hid_init(void)
{
    return -1;
}
void    usb_hid_poll(void)          {}
uint8_t usb_hid_left_held(void)     { return 0u; }
uint8_t usb_hid_right_held(void)    { return 0u; }
uint8_t usb_hid_space_pressed(void) { return 0u; }
uint8_t usb_hid_enter_pressed(void) { return 0u; }
uint8_t usb_hid_r_pressed(void)     { return 0u; }

uint32_t usb_hid_status_word(void)
{
    return 0u;
}

#endif
